// Generated by Wrangler by running `wrangler types`

interface Env {
	PRESENTATION: DurableObjectNamespace<import("./src/index").Presentation>;
	SLIDE: DurableObjectNamespace<import("./src/index").Slide>;
}
